### ISSUE TITLE
Why shift the blockIdx.x?

### ISSUE THREAD

**Issue by twmht** [komrad36/CUDAFLERP#1]
I do not understand the implementation.

Why shift the blockIdx.x by 9 and 1?

https://github.com/komrad36/CUDAFLERP/blob/master/CUDAFLERP.cu#L41

**Comment by komrad36** [comment]
Y direction is independently handled by blockIdx.y. X direction: each thread processes 2 elements, therefore starting index should be offset by threadIdx.x * 2 == threadIdx.x << 1 within a block. As for the block offset: each block has 256 threads in the x dimension. As we said, each one processes 2 elements. Therefore, the block offset should be blockIdx.x * 256 * 2 == blockIdx.x * 512 == blockIdx.x << 9.

**Comment by twmht** [comment]
@komrad36 

I have one more question, Why you use one thread to deal with two elements? Why not use one thread to process one element?

**Comment by komrad36** [comment]
It's faster.

Please try changing the kernel to process 1 element and see which is faster (make sure it's still correct!). Experiment with 1, 2, 4, 8, etc. elements per thread.

There are (at least) two considerations.

The first is that many GPUs are capable of ILP (instruction-level parallelism), so it is actually NOT POSSIBLE to fully utilize the ALUs even if the maximum possible number of threads is running. It is actually necessary to run FEWER threads concurrently, at LOWER occupancy, but with each thread having some amount of independent work (i.e. separate elements so there's no dependency chain), so that the OO (out-of-order execution) engine can fully schedule the ALUs.

The second is that for very short kernels like this one, some GPUs will be limited by the rate at which the command processor can create wavefronts (AMD term) / warps (Nvidia term), so you actually don't want your kernel too short or it will be bottlenecked by wave creation rather than by something intrinsic to the problem (execution, or data, or whatever).

**Comment by twmht** [comment]
@komrad36 

thank you
